language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - "pip install pycrypto"
  - "pip install paramiko"
# command to run tests
script: make tests
